# For Atom Feed
domain: nuclearpengy.github.io
author: Nathan Jeffery

# locations
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

# Handling Reading
safe: false
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

parentsite: https://nuclearpengy.github.io
baseurl: https://nuclearpengy.github.io
permalink: pretty
timezone: Africa/Nairobi

gems:
  - jekyll-sitemap

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      author: "Nathan Jeffery"
      permalink: pretty
      
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "Nathan Jeffery"

  - scope:
      path: "assets/img"
    values:
      image: true
